# Gates for the corpus.
#
# There were none before this file. Every figure in README.md and docs/CORPUS.md came
# from a command someone remembered to type, which is why several of them drifted from
# the data. These targets are the commands; run them instead of remembering them.
#
#     make stats     per-source table (the README Dataset table)
#     make verify    checksum manifest: contents AND coverage
#     make quality   the Data Quality numbers, with the PII gate
#     make lint      ruff over the scripts
#     make check     verify + quality + lint, i.e. everything that can fail

PYTHON ?= python3
SHARDS := shards

# ruff is not vendored. Use it if it is on PATH, otherwise fall back to uvx, which
# fetches it on demand. Both read ruff.toml, so a local run and a CI run agree.
RUFF ?= $(shell command -v ruff >/dev/null 2>&1 && echo ruff || echo 'uvx ruff')

.PHONY: all check stats verify quality lint

all: check

## check: everything that can fail. stats is excluded because it only reports.
check: verify quality lint

## stats: per-source shards, lines, characters, Mon/Myanmar share.
stats:
	$(PYTHON) scripts/shard_stats.py

## verify: check the shards against shards/SHA256SUMS.
#
# Two things have to be true and only one of them is what shasum checks.
#
# 1. The listed files still hash to what the manifest says. `shasum -c` does that.
#    It must run from inside shards/ — the manifest holds bare filenames, so from the
#    repo root every single file reports "No such file or directory".
#
# 2. The manifest covers every shard that exists. `shasum -c` does NOT do that: it
#    only looks at the lines it was given, so it exits 0 on a manifest that has gone
#    stale by omission. That is the failure mode this repo actually had — the manifest
#    was regenerated by hand, and an import that forgot the step left new shards
#    unprotected with a green check. build_shards.py now regenerates it automatically;
#    this target is what catches the case where something else added a file.
verify:
	@cd $(SHARDS) && shasum -a 256 -c SHA256SUMS
	@cd $(SHARDS) && \
	  uncovered=$$(for f in *.txt; do grep -qF "  $$f" SHA256SUMS || echo "  $$f"; done); \
	  if [ -n "$$uncovered" ]; then \
	    echo "FAIL: SHA256SUMS does not cover:"; \
	    echo "$$uncovered"; \
	    echo "shasum -c exits 0 anyway - it only checks the files the manifest lists."; \
	    echo "Regenerate: cd $(SHARDS) && shasum -a 256 *.txt > SHA256SUMS"; \
	    exit 1; \
	  fi; \
	  echo "coverage: SHA256SUMS lists all $$(ls -1 *.txt | wc -l | tr -d ' ') .txt file(s) in $(SHARDS)/"

## quality: the Data Quality figures, and the no-PII gate (--check exits 1 on a violation).
quality:
	$(PYTHON) scripts/data_quality.py --check

## lint: ruff over the scripts, configured by ruff.toml.
lint:
	$(RUFF) check .
